version: '3.8'

services:
  db:
    image: postgres
    container_name: apiuniversityms-db
    environment:
      POSTGRES_DB: universitydb
      POSTGRES_USER: universityuser
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # 👈 пробрасываем на 5433, чтобы не конфликтовал с локальным Postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: