version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: universityMS-postgres
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: university_user
      POSTGRES_PASSWORD: university_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
volumes:
  postgres_data: