CREATE TABLE departments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    short_name        VARCHAR(255)                            NOT NULL,
    slug              VARCHAR(255)                            NOT NULL,
    department_office VARCHAR(255),
    faculty_id        BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE disciplines
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    slug          VARCHAR(255)                            NOT NULL,
    code          VARCHAR(255)                            NOT NULL,
    hours         DOUBLE PRECISION                        NOT NULL,
    course        INTEGER                                 NOT NULL,
    semester      INTEGER                                 NOT NULL,
    type          VARCHAR(255),
    department_id BIGINT,
    lector_id     BIGINT,
    assistant_id  BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_disciplines PRIMARY KEY (id)
);

CREATE TABLE faculties
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    short_name  VARCHAR(255)                            NOT NULL,
    slug        VARCHAR(255)                            NOT NULL,
    dean_office VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_faculties PRIMARY KEY (id)
);

CREATE TABLE grades
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value         INTEGER                                 NOT NULL,
    letter_value  VARCHAR(255),
    student_id    BIGINT,
    discipline_id BIGINT,
    teacher_id    BIGINT,
    grade_type    VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_grades PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number        VARCHAR(255)                            NOT NULL,
    slug          VARCHAR(255)                            NOT NULL,
    curator_id    BIGINT,
    department_id BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE schedule_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    week_type       VARCHAR(255),
    day_of_week     VARCHAR(255),
    pair_number     INTEGER                                 NOT NULL,
    auditory_number VARCHAR(255)                            NOT NULL,
    group_id        BIGINT,
    discipline_id   BIGINT,
    activity_type   VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_schedule_items PRIMARY KEY (id)
);

CREATE TABLE students
(
    user_id        BIGINT           NOT NULL,
    grade_book_num VARCHAR(255)     NOT NULL,
    course         INTEGER          NOT NULL,
    semester       INTEGER          NOT NULL,
    average_score  DOUBLE PRECISION NOT NULL,
    scholarship    DOUBLE PRECISION NOT NULL,
    group_id       BIGINT,
    CONSTRAINT pk_students PRIMARY KEY (user_id)
);

CREATE TABLE teachers
(
    user_id         BIGINT NOT NULL,
    department_id   BIGINT,
    employee_id     VARCHAR(255),
    academic_degree VARCHAR(255),
    academic_title  VARCHAR(255),
    position        VARCHAR(255),
    office_number   VARCHAR(255),
    work_experience INTEGER,
    CONSTRAINT pk_teachers PRIMARY KEY (user_id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    middle_name   VARCHAR(255),
    last_name     VARCHAR(255)                            NOT NULL,
    slug          VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    phone_number  VARCHAR(255)                            NOT NULL,
    photo_url     VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    role          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE schedule_items
    ADD CONSTRAINT uc_d523562b59c6d929970193e43 UNIQUE (week_type, day_of_week, group_id);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_name UNIQUE (name);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_short_name UNIQUE (short_name);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_slug UNIQUE (slug);

ALTER TABLE disciplines
    ADD CONSTRAINT uc_disciplines_code UNIQUE (code);

ALTER TABLE disciplines
    ADD CONSTRAINT uc_disciplines_name UNIQUE (name);

ALTER TABLE disciplines
    ADD CONSTRAINT uc_disciplines_slug UNIQUE (slug);

ALTER TABLE faculties
    ADD CONSTRAINT uc_faculties_name UNIQUE (name);

ALTER TABLE faculties
    ADD CONSTRAINT uc_faculties_short_name UNIQUE (short_name);

ALTER TABLE faculties
    ADD CONSTRAINT uc_faculties_slug UNIQUE (slug);

ALTER TABLE groups
    ADD CONSTRAINT uc_groups_number UNIQUE (number);

ALTER TABLE groups
    ADD CONSTRAINT uc_groups_slug UNIQUE (slug);

ALTER TABLE students
    ADD CONSTRAINT uc_students_grade_book_num UNIQUE (grade_book_num);

ALTER TABLE teachers
    ADD CONSTRAINT uc_teachers_employee UNIQUE (employee_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_photourl UNIQUE (photo_url);

ALTER TABLE users
    ADD CONSTRAINT uc_users_slug UNIQUE (slug);

CREATE INDEX idx_department_created_at ON departments (created_at);

CREATE INDEX idx_department_faculty_created ON departments (faculty_id, created_at DESC);

CREATE INDEX idx_department_faculty_name ON departments (faculty_id, name);

CREATE INDEX idx_department_name ON departments (name);

CREATE INDEX idx_department_short_name ON departments (short_name);

CREATE INDEX idx_department_slug ON departments (slug);

CREATE INDEX idx_discipline_code ON disciplines (code);

CREATE INDEX idx_discipline_course_semester ON disciplines (course, semester);

CREATE INDEX idx_discipline_created_at ON disciplines (created_at);

CREATE INDEX idx_discipline_department_course ON disciplines (department_id, course);

CREATE INDEX idx_discipline_department_course_semester ON disciplines (department_id, course, semester);

CREATE INDEX idx_discipline_department_semester ON disciplines (department_id, semester);

CREATE INDEX idx_discipline_lector_assistant ON disciplines (lector_id, assistant_id);

CREATE INDEX idx_discipline_name ON disciplines (name);

CREATE INDEX idx_discipline_slug ON disciplines (slug);

CREATE INDEX idx_faculty_created_at ON faculties (created_at);

CREATE INDEX idx_faculty_name_asc ON faculties (name);

CREATE INDEX idx_faculty_short_name ON faculties (short_name);

CREATE INDEX idx_faculty_slug ON faculties (slug);

CREATE INDEX idx_grade_created_at ON grades (created_at);

CREATE INDEX idx_grade_student_created ON grades (student_id, created_at DESC);

CREATE INDEX idx_grade_student_discipline ON grades (student_id, discipline_id);

CREATE INDEX idx_grade_student_discipline_created ON grades (student_id, discipline_id, created_at DESC);

CREATE INDEX idx_grade_teacher_created ON grades (teacher_id, created_at DESC);

CREATE INDEX idx_grade_teacher_discipline ON grades (teacher_id, discipline_id);

CREATE INDEX idx_group_created_at ON groups (created_at);

CREATE INDEX idx_group_department_created ON groups (department_id, created_at DESC);

CREATE INDEX idx_group_department_number ON groups (department_id, number);

CREATE INDEX idx_group_number ON groups (number);

CREATE INDEX idx_group_slug ON groups (slug);

CREATE INDEX idx_schedule_auditory ON schedule_items (auditory_number);

CREATE INDEX idx_schedule_auditory_day ON schedule_items (auditory_number, day_of_week);

CREATE INDEX idx_schedule_created_at ON schedule_items (created_at);

CREATE INDEX idx_schedule_day_pair ON schedule_items (day_of_week, pair_number);

CREATE INDEX idx_schedule_day_pair_auditory ON schedule_items (day_of_week, pair_number, auditory_number);

CREATE INDEX idx_schedule_day_pair_group ON schedule_items (day_of_week, pair_number, group_id);

CREATE INDEX idx_schedule_group_week ON schedule_items (group_id, week_type);

CREATE INDEX idx_schedule_group_week_day ON schedule_items (group_id, week_type, day_of_week);

CREATE INDEX idx_schedule_week_day ON schedule_items (week_type, day_of_week);

CREATE INDEX idx_student_average_score ON students (average_score);

CREATE INDEX idx_student_course ON students (course);

CREATE INDEX idx_student_course_semester ON students (course, semester);

CREATE INDEX idx_student_grade_book ON students (grade_book_num);

CREATE INDEX idx_student_group_course ON students (group_id, course);

CREATE INDEX idx_teacher_degree ON teachers (academic_degree);

CREATE INDEX idx_teacher_department_position ON teachers (department_id, position);

CREATE INDEX idx_teacher_department_title ON teachers (department_id, academic_title);

CREATE INDEX idx_teacher_employee_id ON teachers (employee_id);

CREATE INDEX idx_teacher_position ON teachers (position);

CREATE INDEX idx_teacher_title ON teachers (academic_title);

CREATE INDEX idx_user_created_at ON users (created_at);

CREATE INDEX idx_user_email ON users (email);

CREATE INDEX idx_user_first_last_name ON users (first_name, last_name);

CREATE INDEX idx_user_first_name ON users (first_name);

CREATE INDEX idx_user_last_first_name ON users (last_name, first_name);

CREATE INDEX idx_user_last_name ON users (last_name);

CREATE INDEX idx_user_phone ON users (phone_number);

CREATE INDEX idx_user_photo ON users (photo_url);

CREATE INDEX idx_user_role ON users (role);

CREATE INDEX idx_user_slug ON users (slug);

ALTER TABLE departments
    ADD CONSTRAINT FK_DEPARTMENTS_ON_FACULTY FOREIGN KEY (faculty_id) REFERENCES faculties (id) ON DELETE SET NULL;

CREATE INDEX idx_department_faculty ON departments (faculty_id);

ALTER TABLE disciplines
    ADD CONSTRAINT FK_DISCIPLINES_ON_ASSISTANT FOREIGN KEY (assistant_id) REFERENCES teachers (user_id) ON DELETE SET NULL;

CREATE INDEX idx_discipline_assistant ON disciplines (assistant_id);

ALTER TABLE disciplines
    ADD CONSTRAINT FK_DISCIPLINES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;

ALTER TABLE disciplines
    ADD CONSTRAINT FK_DISCIPLINES_ON_LECTOR FOREIGN KEY (lector_id) REFERENCES teachers (user_id) ON DELETE SET NULL;

CREATE INDEX idx_discipline_lector ON disciplines (lector_id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_DISCIPLINE FOREIGN KEY (discipline_id) REFERENCES disciplines (id) ON DELETE SET NULL;

CREATE INDEX idx_grade_discipline ON grades (discipline_id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (user_id) ON DELETE SET NULL;

CREATE INDEX idx_grade_student ON grades (student_id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teachers (user_id) ON DELETE SET NULL;

CREATE INDEX idx_grade_teacher ON grades (teacher_id);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_CURATOR FOREIGN KEY (curator_id) REFERENCES teachers (user_id) ON DELETE SET NULL;

CREATE INDEX idx_group_curator ON groups (curator_id);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

CREATE INDEX idx_group_department ON groups (department_id);

ALTER TABLE schedule_items
    ADD CONSTRAINT FK_SCHEDULE_ITEMS_ON_DISCIPLINE FOREIGN KEY (discipline_id) REFERENCES disciplines (id) ON DELETE SET NULL;

CREATE INDEX idx_schedule_discipline ON schedule_items (discipline_id);

ALTER TABLE schedule_items
    ADD CONSTRAINT FK_SCHEDULE_ITEMS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE SET NULL;

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE SET NULL;

CREATE INDEX idx_student_group ON students (group_id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE teachers
    ADD CONSTRAINT FK_TEACHERS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;

CREATE INDEX idx_teacher_department ON teachers (department_id);

ALTER TABLE teachers
    ADD CONSTRAINT FK_TEACHERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);